# Generated by Django 2.2.6 on 2021-03-04 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_timestamp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
